# Latest Tamarin release (for referring to in various pages)
tamarinrelease: "1.10"
developname: "development branch"
sass:
  style: compact

collections:
  publications:
    output: true
    permalink: /:collection/:name

